[package]
name = 'aptos-nft'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
AptosFramework = { local = "../../../framework/aptos-framework" }
AptosToken = { local = "../../../framework/aptos-token" }


[addreses]
sender = "0xbc465eb8cd06ec98e88b502558298168408705da84f73a2d4032a49ee5baafdb"
# replace the admin_addr with the actual admin address created using CLI
admin_addr = "0x878d94616dd90f877e881ff06caaa4b4f990b7df1a84fa4cb6ea8b625a0bea59"